volumes:
  data:
services:
  db:
    image: mariadb
    container_name: nextjs-cms-mariadb
    hostname: nextjs-cms-mariadb
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - data:/var/lib/mysql
    ports:
      - "6612:3306"
